services:
  - type: web
    name: news-aggregator
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEWS_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
    autoDeploy: true